### PR TITLE
Move to pnpm

### LINKED ISSUE #12: Sometimes scrolling does not work, requireing page load
```
yarn start:simple
```

Expand some folders and see scrolling not work well

### PR DESCRIPTION
**Pull request by timkpaine**
Also fixes #12 
Closes #13

### CODE REVIEW

File: packages/tree-finder/src/element/grid.ts [hunk 1]
```diff
@@ -28,6 +28,10 @@ export class TreeFinderGridElement<
     ) {
         this.model = model;
         this.options = options;
+
+        // wait for registration of regular-table component
+        await customElements.whenDefined("regular-table");
```
Comment (timkpaine) [inline packages/tree-finder/src/element/grid.ts:33]: partial #12 fix

File: packages/tree-finder/src/element/panel.ts [hunk 2]
```diff
@@ -62,7 +62,8 @@ export class TreeFinderPanelElement<T extends IContentRow> extends HTMLElement {
         if (this.options.showFilter) {
             this.filters.init(this._model);
         }
-        this.grid.init(this._model, gridOptions);
+
+        await this.grid.init(this._model, gridOptions);
```
Comment (timkpaine) [inline packages/tree-finder/src/element/panel.ts:66]: partial #12 fix
